<?php

/**
 * Implementation of hook_feeds_plugins().
 */
function feed_xml_parser_feeds_plugins() {
  $path = drupal_get_path('module', 'feed_xml_parser');
  $info = array();
  $info['DxParser'] = array(
    'name' => 'Custom XML parser',
    'description' => 'Parses custom XML data',
    'handler' => array(
      'parent' => 'FeedsParser', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class' => 'CustomParser',
      'file' => 'feed_xml_parser.inc',
      'path' => $path,
    ),
  );
  return $info;
}

function feed_xml_parser_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
